controlPlane:
  mode: standalone
  environment: kubernetes
  service:
    type: ClusterIP
  metrics:
    serviceMonitor:
      enabled: true
  serviceAccount:
    create: true
  resources:
    limits:
      cpu: 1000m
      memory: 512Mi
    requests:
      cpu: 100m
      memory: 128Mi

cni:
  enabled: true
  chained: true
  binDir: /opt/cni/bin
  confDir: /etc/cni/net.d

injector:
  enabled: true
  sidecarContainer:
    resources:
      limits:
        cpu: 1000m
        memory: 512Mi
      requests:
        cpu: 100m
        memory: 128Mi 