{{- $renderedServices := dict }} {{/* Track rendered services by name */}}
{{- range $key, $svc := .Values.services }}
{{- if $svc.enabled }}
{{- if not (hasKey $renderedServices $svc.name) }} {{/* Only render once per unique name */}}
{{- $_ := set $renderedServices $svc.name true }} {{/* Mark as rendered */}}

apiVersion: v1
kind: Service
metadata:
  name: {{ $svc.name }}
spec:
  selector:
    app: {{ $svc.name }}
  ports:
    - port: {{ $svc.port }}
      targetPort: {{ $svc.port }}
      appProtocol: http
---
{{- end }}
{{- end }}
{{- end }}
