apiVersion: kuma.io/v1alpha1
kind: MeshTrafficPermission
metadata:
  name: allow-inter-backend-traffic
  namespace: ecommerce
  labels:
    kuma.io/mesh: default
spec:
  targetRef:
    kind: Dataplane
    labels:
      type: backend   
  from:
  - targetRef:
      kind: MeshSubset
      tags:
        type: backend
    default:
      action: Allow


