apiVersion: v1
kind: Service
metadata:
  name: user-db
  namespace: ecommerce
spec:
  selector:
    app: user-db
  ports:
    - protocol: TCP
      port: 5432
      targetPort: 5432
---
apiVersion: apps/v1
kind: Deployment
metadata:
  name: user-db
  namespace: ecommerce
spec:
  replicas: 1
  selector:
    matchLabels:
      app: user-db
  template:
    metadata:
      labels:
        app: user-db
      annotations:
        kuma.io/sidecar-injection: "false"
    spec:
      containers:
      - name: postgres
        image: postgres:15
        env:
        - name: POSTGRES_USER
          value: myuser
        - name: POSTGRES_PASSWORD
          value: mypassword
        - name: POSTGRES_DB
          value: userdata
        ports:
        - containerPort: 5432
---
apiVersion: v1
kind: Service
metadata:
  name: product-db
  namespace: ecommerce
spec:
  selector:
    app: product-db
  ports:
    - protocol: TCP
      port: 5432
      targetPort: 5432
---
apiVersion: apps/v1
kind: Deployment
metadata:
  name: product-db
  namespace: ecommerce
spec:
  replicas: 1
  selector:
    matchLabels:
      app: product-db
  template:
    metadata:
      labels:
        app: product-db
      annotations:
        kuma.io/sidecar-injection: "false"
    spec:
      containers:
      - name: postgres
        image: postgres:15
        env:
        - name: POSTGRES_DB
          value: productdata
        - name: POSTGRES_USER
          value: myuser
        - name: POSTGRES_PASSWORD
          value: mypassword
        ports:
        - containerPort: 5432
---
apiVersion: v1
kind: Service
metadata:
  name: sales-db
  namespace: ecommerce
spec:
  selector:
    app: sales-db
  ports:
    - protocol: TCP
      port: 5432
      targetPort: 5432
---
apiVersion: apps/v1
kind: Deployment
metadata:
  name: sales-db
  namespace: ecommerce
spec:
  replicas: 1
  selector:
    matchLabels:
      app: sales-db
  template:
    metadata:
      labels:
        app: sales-db
      annotations:
        kuma.io/sidecar-injection: "false"
    spec:
      containers:
      - name: postgres
        image: postgres:15
        env:
        - name: POSTGRES_USER
          value: myuser
        - name: POSTGRES_PASSWORD
          value: mypassword
        - name: POSTGRES_DB
          value: salesdata
        ports:
        - containerPort: 5432 