apiVersion: v1
kind: Service
metadata:
  name: sales-service
  namespace: ecommerce
  labels:
    app: sales-service
spec:
  selector:
    app: sales-service
  ports:
    - protocol: TCP
      port: 8001
      targetPort: 8001
---
apiVersion: apps/v1
kind: Deployment
metadata:
  name: sales-service
  namespace: ecommerce
spec:
  replicas: 2
  selector:
    matchLabels:
      app: sales-service
  template:
    metadata:
      labels:
        app: sales-service
        kuma.io/service: sales-service
    spec:
      containers:
      - name: sales-service
        image: sales-service-img:latest
        imagePullPolicy: Never
        env:
        - name: DATABASE_URL
          value: postgresql://myuser:mypassword@sales-db:5432/salesdata
        ports:
        - containerPort: 8001
      initContainers:
      - name: wait-for-db
        image: postgres:15
        command: ['sh', '-c', 'until pg_isready -h sales-db -p 5432; do echo waiting for sales-db; sleep 2; done; echo "Database is ready. Waiting for 5 seconds..."; sleep 5;'] 