apiVersion: kuma.io/v1alpha1
kind: MeshHTTPRoute
metadata:
  name: http-split-new-service
  namespace: ecommerce
spec:
  targetRef:
    kind: MeshSubset
    tags:
      k8s.kuma.io/service-name: kong-kong-admin
  to:
    - targetRef:
        kind: MeshService
        name: new-service
      rules:
        - matches:
            - path:
                type: PathPrefix
                value: "/"
          default:
            backendRefs:
              - kind: MeshService
                labels:
                  kuma.io/service: new-service
                  version: v1
                weight: {{ .Values.blueWeight }}
              - kind: MeshService
                labels:
                  kuma.io/service: new-service
                  version: v2
                weight: {{ .Values.greenWeight }}
