services:
  control-plane:
    build:
      context: .
      dockerfile: Dockerfile.control-plane
    container_name: kuma-control-plane
    ports:
      - "5681:5681"
    volumes:
      - ./tokens:/tokens
      - ./control_plane:/control_plane
      - ./certs:/certs
    environment:
      - KUMA_GENERAL_TLS_CERT_FILE=/certs/server.crt
      - KUMA_GENERAL_TLS_KEY_FILE=/certs/server.key
    networks:
      kuma-network:
        ipv4_address: 192.168.0.1
    healthcheck:
      test: ["CMD", "curl", "-f", "http://localhost:5681/"]
      interval: 10s
      timeout: 5s
      retries: 5
      start_period: 10s

  jaeger:
    image: jaegertracing/jaeger:2.6.0
    environment:
      - COLLECTOR_ZIPKIN_HTTP_PORT=9411
    ports:
      - "16686:16686"   # UI
      - "6831:6831/udp" # UDP para traces (Jaeger Thrift)
      - "9411:9411"
    networks:
      kuma-network:
        ipv4_address: 192.168.0.50

networks:
  kuma-network:
    driver: bridge
    ipam:
      config:
        - subnet: 192.168.0.0/24
          gateway: 192.168.0.254
          ip_range: 192.168.0.96/28

volumes:
  user_db_data:
  kong_db_data:
  product_db_data:
  sales_db_data:
