admin:
  enabled: true
  http:
    enabled: true
    servicePort: 8001
    containerPort: 8001
  tls:
    enabled: false  # or true, if you want HTTPS

proxy:
  enabled: true  
  type: NodePort
  http:
    nodePort: 30080  # NodePort for HTTP access