apiVersion: v1
kind: Secret
metadata:
  name: user-jwt
  namespace: ecommerce
  labels:
    konghq.com/credential: jwt
  annotations:
    konghq.com/consumer: frontend 
stringData:
  kongCredType: jwt
  key: frontend
  algorithm: HS256
  secret: your_secret_key


  